apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attic
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    haproxy-ingress.github.io/proxy-body-size: "1g"
spec:
  ingressClassName: haproxy
  tls:
    - secretName: tls-nix-store
      hosts: [ babe-do-you-need-anything-from-the-nix.store ]
  rules:
    - host: babe-do-you-need-anything-from-the-nix.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: attic-server
                port:
                  name: http
