apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
  - manifests/namespace.yml
  - manifests/rbac.yml
  - manifests/authentik-server.yml
  - manifests/authentik-worker.yml
  - manifests/ingress.yml

images:
  - name: ghcr.io/goauthentik/server
    newTag: "2025.12"

configMapGenerator:
  - name: authentik-env
    envs:
      - ./config/authentik.env

generators:
  - ./secret-generator.yml
