# ref: https://artifacthub.io/packages/helm/haproxy-ingress/haproxy-ingress
controller:
  livenessProbe:
    port: 10254
  readinessProbe:
    port: 10254
  config:
    proxy-body-size: "1k"
    bind-http: ":::80,:80"
    bind-https: ":::443,:443"
  ingressClassResource:
    enabled: true
    default: false
  service:
    externalTrafficPolicy: Local      

