apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haproxy-ingress

resources:
  - manifests/namespace.yml

patches:
  - target:
      version: v1
      kind: Service
      name: haproxy-ingress
      namespace: haproxy-ingress
    path: lb-service.patch.yml

helmCharts:
  - name: haproxy-ingress
    repo: https://haproxy-ingress.github.io/charts
    releaseName: haproxy-ingress
    version: "0.15.0"
    valuesFile: haproxy-ingress.values.yaml
    namespace: haproxy-ingress
    includeCRDs: false
