apiVersion: v1
kind: Service
metadata:
  name: website-riddles
  labels: &labels
    app.kubernetes.io/name: website-riddles
    app.kubernetes.io/component: riddles-server
spec:
  selector: *labels
  ipFamilyPolicy: SingleStack
  ipFamilies: [ IPv6 ]
  ports:
    - name: http
      port: 80
      targetPort: http
