apiVersion: v1
kind: List
items:

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: immich-worker
      labels: &labels
        app.kubernetes.io/name: immich-worker
        app.kubernetes.io/component: background-worker
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels: *labels
                  topologyKey: kubernetes.io/hostname
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: immich-data
          containers:
            - name: immich
              image: ghcr.io/immich-app/immich-server
              env:
                - name: IMMICH_WORKERS_EXCLUDE
                  value: api
              envFrom:
                - secretRef:
                    name: immich-env
              volumeMounts:
                - name: data
                  mountPath: /data
              ports:
                - name: metrics
                  containerPort: 8081
                - name: svc-metrics
                  containerPort: 8082
