apiVersion: v1
kind: List
items:

  # service
  - apiVersion: v1
    kind: Service
    metadata:
      name: photoprism-server
      labels: &labels
        app.kubernetes.io/name: photoprism-server
        app.kubernetes.io/component: webserver
    spec:
      selector: *labels
      ports:
        - name: http
          port: 2342
          targetPort: http

  # webserver deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: photoprism-server
      labels: *labels
    spec:
      #replicas: 1 # photoprism explicitly mentions not supporting horizontal scaling
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          volumes:
            - name: photoprism-originals
              persistentVolumeClaim:
                claimName: photoprism-originals
            - name: photoprism-storage
              persistentVolumeClaim:
                claimName: photoprism-storage
          containers:
            - name: photoprism
              image: "docker.io/photoprism/photoprism"
              envFrom:
                - configMapRef:
                    name: photoprism-env
                - secretRef:
                    name: photoprism-env
              volumeMounts:
                - name: photoprism-originals
                  mountPath: /photoprism/originals
                - name: photoprism-storage
                  mountPath: /photoprism/storage
              ports:
                - name: http
                  containerPort: 2342
              readinessProbe:
                httpGet:
                  port: http
                  path: /library/login

  # storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: photoprism-originals
    spec:
      accessModes: [ ReadWriteMany ]
      resources:
        requests:
          storage: "1Ti"

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: photoprism-storage
    spec:
      accessModes: [ ReadWriteMany ]
      resources:
        requests:
          storage: "200Gi"
