apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: >-
      traefik-compress@kubernetescrd,
      traefik-redirect-tls@kubernetescrd,
      traefik-secure-headers@kubernetescrd
spec:
  ingressClassName: haproxy
  tls:
    - hosts: [ whoami.aut-sys.de ]
      secretName: tls-whoami.aut-sys.de
  rules:
  - host: whoami.aut-sys.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              name: web
