apiVersion: batch/v1
kind: CronJob
metadata:
  name: website-webmentions
  labels: &labels
    app.kubernetes.io/name: website
    app.kubernetes.io/component: webmention-sending
spec:
  schedule: "@daily"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels: *labels
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels: *labels
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 10000
          volumes:
            - name: state
              persistentVolumeClaim:
                claimName: homepage-state
          containers:
            - name: homepage
              image: git.hanse.de/lilly/homepage
              command: [ "/bin/sh", "-c" ]
              args:
                - |
                  /usr/local/src/homepage/manage.py discover-webmentions
                  /usr/local/src/homepage/manage.py send-webmentions
                  /usr/local/src/homepage/manage.py show-webmentions
              envFrom:
                - secretRef:
                    name: website-env
              volumeMounts:
                - name: state
                  mountPath: /var/lib/homepage/
              resources:
                requests:
                  cpu: "100m"
                limits:
                  memory: "200Mi"
