apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-budget
  labels:
    app.kubernetes.io/name: actual-budget
    app.kubernetes.io/component: webserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: haproxy
  tls:
    - secretName: tls-budget.aut-sys.de
      hosts: [ budget.aut-sys.de ]
  rules:
    - host: budget.aut-sys.de
      http: &httpConfig
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-budget
                port:
                  name: http
