apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    profile: shortlived
    email: li@lly.sh
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          class: haproxy
          serviceType: ClusterIP
          podTemplate:
            spec:
              priorityClassName: custom-critical
