apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: photoprism

images:
  - name: "docker.io/photoprism/photoprism"
    newTag: "250707"

resources:
  - manifests/namespace.yaml
  - manifests/photoprism-webserver.yaml
  - manifests/ingress.yml

configMapGenerator:
  - name: photoprism-env
    envs:
      - config/photoprism.env

generators:
  - ./secret-generator.yml
