# ref: https://github.com/viaduct-ai/kustomize-sops
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: photoprism-env
    envs:
      - "config/photoprism.secret.env"
