apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "github.com/rancher/local-path-provisioner/deploy?ref=v0.0.34"

patches:
  - target:
      group: storage.k8s.io
      kind: StorageClass
      name: local-path
    patch: |
      - op: replace
        path: /volumeBindingMode
        value: Immediate
      - op: add
        path: /metadata/annotations
        value:
          "storageclass.kubernetes.io/is-default-class": "true"
        

configMapGenerator:
  - name: local-path-config
    namespace: "local-path-storage"
    behavior: merge
    files:
      - "config.json=config.json"
